services:
  # MongoDB Service
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: AhmadSh-ats
      MONGO_INITDB_ROOT_PASSWORD: ahmadali1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks :
      - Collabration-networks
  
  # Backend (Node.js / Express) Service
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: backend
    environment:
      PORT: 5000
      MONGO_URI: mongodb+srv://AhmadSh-ats:ahmadali1@cluster0.1o1wb3p.mongodb.net/ColabrationTool
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
    - ./Server:/app
    - /app/node_modules
    - ./Server/node_modules:/app/node_modules
    networks :
      - Collabration-networks
  
  # Frontend (React) Service
  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks :
      - Collabration-networks
    volumes:
      - ./Client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  mongo-data:


networks:
  Collabration-networks:
    driver: bridge